on: push

jobs:
  a:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - ./asdf:/test

    steps:
      - name: run
        run: pwd && ls -al && ls -al /test