on: push

defaults:
  run:
    shell: bash

jobs:
  a:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      volumes:
        - /__w/test/test/asdf:/test

    steps:
      - name: run
        run: pwd && ls -al && ls -al /test